// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-ebpf-sdk-go/pkg/elfparser (interfaces: AWSeBpfSdkAPIs)

// Package mock_elfparser is a generated GoMock package.
package mock_elfparser

import (
	reflect "reflect"

	elfparser "github.com/aws/aws-ebpf-sdk-go/pkg/elfparser"
	maps "github.com/aws/aws-ebpf-sdk-go/pkg/maps"
	gomock "github.com/golang/mock/gomock"
)

// MockAWSeBpfSdkAPIs is a mock of AWSeBpfSdkAPIs interface.
type MockAWSeBpfSdkAPIs struct {
	ctrl     *gomock.Controller
	recorder *MockAWSeBpfSdkAPIsMockRecorder
}

// MockAWSeBpfSdkAPIsMockRecorder is the mock recorder for MockAWSeBpfSdkAPIs.
type MockAWSeBpfSdkAPIsMockRecorder struct {
	mock *MockAWSeBpfSdkAPIs
}

// NewMockAWSeBpfSdkAPIs creates a new mock instance.
func NewMockAWSeBpfSdkAPIs(ctrl *gomock.Controller) *MockAWSeBpfSdkAPIs {
	mock := &MockAWSeBpfSdkAPIs{ctrl: ctrl}
	mock.recorder = &MockAWSeBpfSdkAPIsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSeBpfSdkAPIs) EXPECT() *MockAWSeBpfSdkAPIsMockRecorder {
	return m.recorder
}

// IncreaseRlimit mocks base method.
func (m *MockAWSeBpfSdkAPIs) IncreaseRlimit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseRlimit")
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseRlimit indicates an expected call of IncreaseRlimit.
func (mr *MockAWSeBpfSdkAPIsMockRecorder) IncreaseRlimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseRlimit", reflect.TypeOf((*MockAWSeBpfSdkAPIs)(nil).IncreaseRlimit))
}

// LoadBpfFile mocks base method.
func (m *MockAWSeBpfSdkAPIs) LoadBpfFile(arg0 string) (map[string]elfparser.BpfData, map[string]maps.BpfMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadBpfFile", arg0)
	ret0, _ := ret[0].(map[string]elfparser.BpfData)
	ret1, _ := ret[1].(map[string]maps.BpfMap)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoadBpfFile indicates an expected call of LoadBpfFile.
func (mr *MockAWSeBpfSdkAPIsMockRecorder) LoadBpfFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadBpfFile", reflect.TypeOf((*MockAWSeBpfSdkAPIs)(nil).LoadBpfFile), arg0)
}

// RecoverAllBpfProgramsAndMaps mocks base method.
func (m *MockAWSeBpfSdkAPIs) RecoverAllBpfProgramsAndMaps() (map[string]elfparser.BpfData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverAllBpfProgramsAndMaps")
	ret0, _ := ret[0].(map[string]elfparser.BpfData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecoverAllBpfProgramsAndMaps indicates an expected call of RecoverAllBpfProgramsAndMaps.
func (mr *MockAWSeBpfSdkAPIsMockRecorder) RecoverAllBpfProgramsAndMaps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverAllBpfProgramsAndMaps", reflect.TypeOf((*MockAWSeBpfSdkAPIs)(nil).RecoverAllBpfProgramsAndMaps))
}

// RecoverGlobalMaps mocks base method.
func (m *MockAWSeBpfSdkAPIs) RecoverGlobalMaps() (map[string]maps.BpfMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverGlobalMaps")
	ret0, _ := ret[0].(map[string]maps.BpfMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecoverGlobalMaps indicates an expected call of RecoverGlobalMaps.
func (mr *MockAWSeBpfSdkAPIsMockRecorder) RecoverGlobalMaps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverGlobalMaps", reflect.TypeOf((*MockAWSeBpfSdkAPIs)(nil).RecoverGlobalMaps))
}
